### PR TITLE
Adding generic hooks (POST_DEPLOY_GROUP, PRE_REMOVE_GROUP) to support service-specific logic

### PR DESCRIPTION
**Pull request by zachidan**

### CODE REVIEW

**Comment by nfritze** [comment]
Looks reasonable, going to do some verification, may take a bit (rather swamped at the moment)

**Comment by jgarcows** [comment]
Line 54 should be:
`elif [[ "${STATUS}" =~ "CREATE_FAILED" ]]; then`

and then line 56 should be:
`elif [[ "${STATUS}" =~ "FAILED" ]]; then`

**Comment by zachidan** [comment]
@jgarcows I've removed Lines 56 and 57 because they are NOT necessary.

In general, the update here is to make the code more robust to the status strings. It looks that new strings are added (e.g., NETWORK_FAILED), but the code was NOT ready for the new strings.

In addition, it does not really matter what the reason is, we just need to know at this phase whether the group was created successfully or not.

**Comment by jgarcows** [comment]
Looks good and tested locally.

**Pull request merged**
